# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Tony/Desktop/project_1/project_1.srcs/sources_1/ip/clk_5Mhz/clk_5Mhz.xci
# IP: The module: 'clk_5Mhz' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Tony/Desktop/project_1/project_1.srcs/sources_1/ip/clk_5Mhz/clk_5Mhz_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_5Mhz'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/Tony/Desktop/project_1/project_1.srcs/sources_1/ip/clk_5Mhz/clk_5Mhz.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_5Mhz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/Tony/Desktop/project_1/project_1.srcs/sources_1/ip/clk_5Mhz/clk_5Mhz_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_5Mhz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/Tony/Desktop/project_1/project_1.srcs/sources_1/ip/clk_5Mhz/clk_5Mhz.xci
# IP: The module: 'clk_5Mhz' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Tony/Desktop/project_1/project_1.srcs/sources_1/ip/clk_5Mhz/clk_5Mhz_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_5Mhz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/Tony/Desktop/project_1/project_1.srcs/sources_1/ip/clk_5Mhz/clk_5Mhz.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_5Mhz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/Tony/Desktop/project_1/project_1.srcs/sources_1/ip/clk_5Mhz/clk_5Mhz_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_5Mhz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
