# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/lab1_4_2/Basys3_Master.xdc

# IP: ip/clk_5Mhz/clk_5Mhz.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_5Mhz || ORIG_REF_NAME==clk_5Mhz} -quiet] -quiet
