@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Tue Apr 14 12:08:06 -1000 2020
REM SW Build 2708876 on Wed Nov  6 21:40:23 MST 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim grey_code_generator_tb_behav -key {Behavioral:sim_1:Functional:grey_code_generator_tb} -tclbatch grey_code_generator_tb.tcl -log simulate.log"
call xsim  grey_code_generator_tb_behav -key {Behavioral:sim_1:Functional:grey_code_generator_tb} -tclbatch grey_code_generator_tb.tcl -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
