# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Tony/Desktop/lab8_2_1/lab8_2_1.srcs/sources_1/ip/counter_1/counter.xci
# IP: The module: 'counter' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Tony/Desktop/lab8_2_1/lab8_2_1.srcs/sources_1/ip/counter_1/counter_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'counter'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/Tony/Desktop/lab8_2_1/lab8_2_1.srcs/sources_1/ip/counter_1/counter.xci
# IP: The module: 'counter' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Tony/Desktop/lab8_2_1/lab8_2_1.srcs/sources_1/ip/counter_1/counter_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'counter'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
